# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-21 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'running'), (1, 'complete')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=60)),
                ('answer', models.FileField(max_length=1024, upload_to=main.models.get_file_path)),
                ('truth', models.FileField(max_length=1024, upload_to=main.models.get_file_path)),
                ('generated_k_folder', models.BooleanField(default=False)),
                ('kfold', models.IntegerField(null=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'decision-making'), (1, 'single label'), (2, 'numeric')], default=0)),
                ('redundancy', models.TextField(null=True)),
                ('quality', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='execution',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Method'),
        ),
        migrations.AddField(
            model_name='execution',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Submission'),
        ),
    ]
